#include <bits/stdc++.h>
using namespace std;

#define ll long long
#define ull unsigned long long
#define pb push_back
#define all(v) v.begin(), v.end()
#define rall(v) v.rbegin(), v.rend()
#define sz(x) (int)(x).size()
#define YES cout << "YES\n";
#define NO cout << "NO\n";
#define MOD 1000000007
#define INF 1e18
#define FAST_IO ios::sync_with_stdio(false); cin.tie(nullptr);


class Solution {
public:
    void solve() {
      
        ll n;
        cin >> n;

      
    }
};

int main() {
    FAST_IO;
    ll t;
    cin >> t;
    
    while (t--) {
        Solution s;
        s.solve();
    }

    return 0;
}
